### ISSUE TITLE
使用しているライブラリが添付されていない。

### ISSUE THREAD

**Issue by ghost** [kwakahara/sutdy_making_201408#1]
リポジトリから落としたら KadaiException.jar がないと言われてしまいました。

**Comment by kwakahara** [comment]
承知しました。
確認して明日の9時前に再度提出させていただきます。

**Comment by kwakahara** [comment]
本日確認いたしましところ、
https://github.com/kwakahara/sutdy_making_201408/commit/72c56586c595659cd7fec440d4e4f1d96d4aac5f
こちらの方にはKadaiException.jarがアップロードされているのが確認できていますので、何かしらのアップロードの方法が間違っていたと予想していますが、原因が特定できませんでした。
アップロード方法としてはEclipseのEGitを用いてプロジェクトのコミットを行いましたが、この方法では何か問題があるのでしょうか。

**Comment by ghost** [comment]
参照ではなくjarがコミットされていないということです。

**Comment by TakamasaSugiura** [comment]
確認しました。
JARファイルは上がっていますが、クラスパスの設定が変です。
若原PCにおけるパスが設定されているため、そのままでは他のPCでは使用できません。
必要なライブラリはプロジェクトの中に含め、外部ライブラリ設定にしないようにしましょう。
![wakahara](https://cloud.githubusercontent.com/assets/7827645/5376698/df0faa20-80bc-11e4-926f-bc2172ad8a0c.JPG)
↑若原PCのパスがセットされているところは、杉浦PCでは使用できないので、赤いバツがついている。
@93de13b

**Comment by TakamasaSugiura** [comment]
コンパイルエラーにならないことを確認しました。
@c80eb36
