### ISSUE TITLE
課題指摘事項5 ストリームがクローズされない恐れがある点について

### ISSUE THREAD

**Issue by TakamasaSugiura** [kwakahara/sutdy_making_201408#6]
「readFile」メソッドの中の処理は次のようになっています。

``` Java
        try {
            FileInputStream input = new FileInputStream(fileName);
            BufferedReader fileLine = openTextFileR(input , "UTF-8");
// (略)
            fileLine.close();

            return line;

        } catch (FileNotFoundException e) {
            throw new KadaiException(ErrorCode.FILE_IN_OUT);
        } catch (IOException e) {
            throw new KadaiException(ErrorCode.FILE_IN_OUT);
        } catch (Exception e) {
            throw new KadaiException(ErrorCode.OTHER_ERROR);
        }
```

中の処理で例外が発生してcatchされた場合、fileLineはクローズされずに残ってしまいます。(ファイルが開きっぱなしになります。)

@d6177ed

**Comment by ghost** [comment]
補足というか横槍ですが。。
ここはJava7のtry-with-resourcesを使うとスマートに解決できますね^^

**Comment by kwakahara** [comment]
例外処理についてお訊ねしたいことがございます。

FileInputStream input = new FileInputStream(fileName);
BufferedReader fileLine = openTextFileR(input , "UTF-8");
try {
// (略)

} catch (FileNotFoundException e) {
    throw new KadaiException(ErrorCode.FILE_IN_OUT);
} catch (IOException e) {
    throw new KadaiException(ErrorCode.FILE_IN_OUT);
} catch (Exception e) {
    throw new KadaiException(ErrorCode.OTHER_ERROR);
}
finally{
    fileLine.close();
}

とするとtryの前で宣言されているFileInputStream input = new FileInputStream(fileName);の個所で発生した例外に対しての処理が何も記述されていないと思います。
ですので、本来であればこの個所もtry-catchで囲うべきだと思うのですが、このことについて言及されている本やサイトを見た記憶がありませんので、何かしらの理由があるのでしたらご教授願います。

**Comment by TakamasaSugiura** [comment]
本はどうだか知りませんが、ネット上に転がっているソースは例外処理をはしょっていることが大半ですので、注意しましょう。

まず、以下のように単純にtry-catchで囲む手を思いつくと思いますが、これはうまくいきません。(コンパイルエラーになります。)

``` Java
try{
    FileInputStream fs = new FileInputStream("テスト.txt");
    // 略
}
finally{
    if(null != fs){ // ←不明な変数が使用されているため、コンパイルエラー
        fs.close();
    }
}
```

理由は、tryの括弧の中で宣言された、変数を、finallyの括弧の中で使用できないからです。
次のような例と同じです。

``` Java
if(0 == i){
    int l = 0;
    l++;
}
else {
    l--; // こちらではlが定義されていないので、エラー
}
```

finallyの中で定義すれば、とりあえずコンパイルは通りますが、tryの中の変数とは別物ですので、まったく意味のない処理になってしまいます。

``` Java
try{
    FileInputStream fs = new FileInputStream("テスト.txt");
    // 略
}
finally{
    // ↓ コンパイルは通るが上の変数とは別物なので、意味が無い、というかバグそのもの。
    FileInputStream fs = new FileInputStream("テスト.txt"); 
    if(null != fs){
        fs.close();
    }
}
```

ですので、括弧の外側で変数宣言して、それがtryの中でも、finallyの中でも使用できるようにする必要があります。

``` Java
FileInputStream fs = new FileInputStream("テスト.txt");
try{
    // 略
}
finally{
    if(null != fs){
        fs.close();
    }
}
```

ただし、FileInputStreamのコンストラクタはFileNotFoundExceptionをthrowする恐れがありますので、それをキャッチしたければ、コンストラクタをtryの中で呼ぶ必要があります。

``` Java
FileInputStream fs = null;
try{
    fs = new FileInputStream("テスト.txt");
    // 略
}
catch(Exception ex){
    // 略
}
finally{
    if(null != fs){
        fs.close();
    }
}
```

こうすれば、コンストラクタで発生した例外もキャッチできます。

ついでに・・・
変数の宣言ですが

``` Java
FileInputStream fs = null;
```

を

``` Java
FileInputStream fs;
```

と、「 = null」を書かないということは今回はできません。
Javaの言語仕様に初期化せずに変数を使用できない、というルールがあり、
tryの直後でエラーが発生した場合、初期化されずに変数の比較などが行われるとJavaが考えるからです。
以下はコンパイルOK。

``` Java
// gはグローバル変数

int a = 1;
if(0 == a){ // aは1で初期化されているからOK
    // 略
}

int l;
if(0 == g){
    l = 1;
}
else {
    l = 2;
}
if(2 == l){ // これ以前でlは1か2に確実に初期化されているからOK
    // 略
}
```

処理の抜けチェックに使用する人もいます。

``` Java
int l;
if(0 == i){
    l = 1;
}
else (1 == i){
    l = 2;
}
else {
    // lの初期化処理に抜けがある！
}
return l; // 初期化処理に抜けがあり、初期化されていない変数が返される可能性がある→コンパイルエラー
```

上の例ですと、elseの中でlの初期化処理が無いため、コンパイルエラーとなります。
コンパイルエラーは出てうれしいものではありませんが、コンパイルが通った後のバグよりも見つけやすいので、こんなチェックをする人もいます。

変数を変な値で初期化すると、思わぬバグを生むことがあります。

``` Java
int l = 21949; // ←なんだろう、これは？
if(0 == i){
    l = 1;
}
else (1 == i){
    l = 2;
}
else {
    // lの設定し忘れ
}
// 最初に変な値で初期化されているので、たとえelseの中で再設定を忘れていたとしてもコンパイルが通る。
return l; 
```

規約の「無意味な値で初期化しない」はこのあたりに関係しているのです。

**Comment by TakamasaSugiura** [comment]
readerクラスの初期化処理が中途半端にバラバラになっています(readFileとopenTextFileRとで分かれている)が、どちらかにした方がわかりやすくなります。
@dc193e1

**Comment by TakamasaSugiura** [comment]
修正確認しました。
(ただし、このtry-with-resources文はJava7以降の機能ですので、
Java6の環境で作る場合は使用できません。注意してください。)
@dd5b40a
